---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: k8s-cleanup
  namespace: kube-system
spec:
  schedule: "*/1 * * * *"
  # schedule: "0 */3 * * *"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        metadata:
          name: k8s-cleanup
        spec:
          restartPolicy: OnFailure
          serviceAccountName: k8s-cleanup
          containers:
            - name: k8s-cleanup
              image: jonathanbaraldi/k8s-cleanup
              command: ["/bin/bash", "/bin/k8s-clean.sh"]
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 100m
                  memory: 50Mi
          nodeSelector:
             role: master